const areas=[
{slug:'software',title:'Desenvolvimento de Software',summary:'Plataformas web, mobile, desktop, APIs e sistemas empresariais sob medida para operações críticas.',items:['Aplicações Web responsivas','Apps Android/iOS','Sistemas desktop','ERPs e CRMs personalizados','APIs seguras','Integrações com pagamentos, stock e faturação']},
{slug:'infraestrutura',title:'Infraestrutura Tecnológica',summary:'Redes, servidores, cloud e virtualização desenhados para continuidade, escala e controlo.',items:['Redes estruturadas','Servidores e storage','Cloud computing','Virtualização','Monitorização','Planos de continuidade']},
{slug:'seguranca',title:'Segurança Informática',summary:'Proteção preventiva e operacional para dados, identidades, dispositivos e ambientes corporativos.',items:['Auditorias técnicas','Hardening','Backups e recuperação','Monitorização','Políticas de acesso','Resposta a incidentes']},
{slug:'assistencia-tecnica',title:'Assistência Técnica',summary:'Suporte especializado para computadores, impressoras, redes e servidores com atendimento ágil.',items:['Diagnóstico','Reparação','Manutenção preventiva','Helpdesk','Suporte remoto','Contratos empresariais']},
{slug:'comercio',title:'Comércio de Equipamentos',summary:'Venda consultiva de computadores, portáteis, impressoras, acessórios e soluções completas.',items:['Computadores empresariais','Portáteis','Impressoras','Consumíveis','Acessórios','Instalação e configuração']},
{slug:'aksanet',title:'AksaNet',summary:'Provedor de internet preparado para residências, PME e instituições que precisam de conectividade fiável.',items:['Planos residenciais','Planos empresariais','Instalação técnica','Cobertura local','Suporte ao cliente','Monitorização da ligação']},
{slug:'farmacia-sixsilvas',title:'Farmácia SixSilvas',summary:'Atendimento farmacêutico institucional com produtos, orientação, entrega e gestão de receitas.',items:['Medicamentos','Produtos de saúde','Entrega','Receitas','Aconselhamento','Contacto rápido']}
];
const nav=[['/','Home'],['/sobre','Sobre Nós'],['/areas/software','Áreas'],['/solucoes/minha-farmacia-online','Soluções'],['/portfolio','Portfólio'],['/blog','Blog'],['/carreiras','Carreiras'],['/contactos','Contactos']].map(([href,label])=>({href,label}));
const app=document.querySelector('#app');
const icon=(t)=>`<span class="icon" aria-hidden="true">${t}</span>`;
const shell=(content)=>`<header class="top"><nav aria-label="Navegação principal"><a class="brand" href="/" data-link><span>Six</span>Silvas</a><button class="menu" aria-label="Abrir menu">☰</button><div class="links">${nav.map(n=>`<a href="${n.href}" data-link>${n.label}</a>`).join('')}</div><a class="navcta" href="/contactos" data-link>Falar com especialista</a></nav></header><main id="conteudo">${content}</main>${footer()}`;
const footer=()=>`<footer><div class="grid four"><div><h3>SixSilvas</h3><p>Comércio, Serviços e Tecnologias para organizações que querem crescer com segurança, velocidade e inovação.</p></div><div><h4>Negócios</h4>${areas.slice(0,5).map(a=>`<a href="/areas/${a.slug}" data-link>${a.title}</a>`).join('')}</div><div><h4>Ecossistema</h4><a href="/areas/aksanet" data-link>AksaNet</a><a href="/areas/farmacia-sixsilvas" data-link>Farmácia SixSilvas</a><a href="/solucoes/minha-farmacia-online" data-link>Minha Farmácia Online</a></div><div><h4>Contacto</h4><p>WhatsApp: +244 900 000 000<br>Email: geral@sixsilvas.com<br>Horário: Segunda a Sábado</p></div></div><small>© ${new Date().getFullYear()} SixSilvas. Todos os direitos reservados.</small></footer>`;
const cards=(xs)=>`<div class="grid cards">${xs.map(x=>`<article class="card"><b>${x.tag??'SixSilvas'}</b><h3>${x.title}</h3><p>${x.body}</p></article>`).join('')}</div>`;
function home(){return shell(`<section class="hero"><div><p class="eyebrow">Tecnologia, serviços e confiança</p><h1>Soluções digitais para empresas que querem operar melhor, crescer mais rápido e proteger o futuro.</h1><p>A SixSilvas combina desenvolvimento de software, infraestrutura, segurança, internet, comércio tecnológico e serviços farmacêuticos numa proposta integrada para empresas, instituições públicas e clientes particulares.</p><div class="actions"><a class="btn primary" href="/contactos" data-link>Solicitar proposta</a><a class="btn ghost" href="/areas/software" data-link>Explorar serviços</a></div></div><div class="visual" role="img" aria-label="Ilustração tecnológica corporativa"><span></span><span></span><span></span></div></section><section>${sectionTitle('Áreas de negócio','Uma operação multidisciplinar para entregar tecnologia, conectividade, suporte e valor institucional.')}${cards(areas.map(a=>({title:a.title,body:a.summary,tag:'Área'})))}</section><section class="split"><div>${sectionTitle('Produtos próprios','Soluções preparadas para escalar com o seu negócio.')}</div><div class="panel"><h3>Minha Farmácia Online</h3><p>Plataforma para farmácias venderem, receberem receitas, gerir entregas, produtos, clientes e relatórios com arquitetura modular e integrações futuras.</p><a href="/solucoes/minha-farmacia-online" data-link>Conhecer solução →</a></div></section><section>${sectionTitle('Diferenciais','Porque organizações escolhem a SixSilvas')}${cards([{title:'Visão integrada',body:'Da estratégia ao suporte, conectamos software, infraestrutura, segurança e operação.'},{title:'Entrega profissional',body:'Processos claros, documentação, acompanhamento e foco em resultado mensurável.'},{title:'Inovação aplicável',body:'IA, cloud e automação com objetivos práticos: reduzir custos e aumentar eficiência.'}])}</section><section class="numbers"><div><strong>12+</strong><span>áreas de atuação</span></div><div><strong>24/7</strong><span>visão de suporte</span></div><div><strong>360º</strong><span>ecossistema tecnológico</span></div><div><strong>AA</strong><span>acessibilidade como meta</span></div></section><section>${sectionTitle('Clientes, parceiros e depoimentos','Estrutura pronta para logos, casos de sucesso e provas sociais.')}${cards([{title:'Instituições públicas',body:'Soluções com foco em continuidade, segurança e transparência.'},{title:'PME e empresas',body:'Tecnologia prática para produtividade, vendas e gestão.'},{title:'Saúde e farmácias',body:'Sistemas e serviços adaptados a ambientes sensíveis.'}])}</section><section class="cta"><h2>Pronto para transformar a sua operação?</h2><p>Converse com a SixSilvas e receba uma recomendação técnica para o seu contexto.</p><a class="btn primary" href="/contactos" data-link>Agendar contacto</a></section>`)}
const sectionTitle=(a,b)=>`<div class="section-title"><p class="eyebrow">SixSilvas</p><h2>${a}</h2><p>${b}</p></div>`;
function about(){return shell(`<section class="pagehead"><h1>Sobre Nós</h1><p>A SixSilvas nasce para aproximar tecnologia, comércio, serviços e inovação das organizações que precisam de parceiros confiáveis.</p></section>${cards([{title:'Missão',body:'Criar soluções tecnológicas e serviços de alto impacto que simplificam processos, protegem dados e melhoram a vida das pessoas.'},{title:'Visão',body:'Ser referência nacional em tecnologia corporativa, conectividade, transformação digital e serviços integrados.'},{title:'Valores',body:'Ética, qualidade, inovação, responsabilidade, proximidade com o cliente e melhoria contínua.'}])}<section>${sectionTitle('Cultura e compromissos','Trabalhamos com rigor técnico, comunicação transparente e foco na longevidade das soluções.')}${timeline(['Fundação com foco em comércio e suporte tecnológico','Expansão para desenvolvimento de software e sistemas empresariais','Integração de cloud, segurança, redes e assistência técnica','Construção do ecossistema AksaNet, Farmácia SixSilvas e soluções próprias'])}</section>`)}
function area(slug){const a=areas.find(x=>x.slug===slug)||areas[0];return shell(`<section class="pagehead"><p class="eyebrow">Área de negócio</p><h1>${a.title}</h1><p>${a.summary}</p></section><section class="grid cards">${a.items.map(i=>`<article class="card">${icon('✦')}<h3>${i}</h3><p>Serviço desenhado com diagnóstico, implementação, documentação e acompanhamento para garantir valor real.</p></article>`).join('')}</section>${slug==='aksanet'?pricing():''}<section class="faq"><h2>Perguntas frequentes</h2>${['Como solicitar uma proposta?','A SixSilvas atende empresas e particulares?','Existe suporte após a implementação?'].map(q=>`<details><summary>${q}</summary><p>Sim. A equipa avalia o contexto, recomenda a melhor abordagem e acompanha o cliente durante e após a entrega.</p></details>`).join('')}</section>`)}
const pricing=()=>`<section>${sectionTitle('Planos AksaNet','Planos ajustáveis conforme cobertura, velocidade e necessidade do cliente.')}${cards([{title:'Residencial',body:'Internet para casa, streaming, estudo e comunicação.'},{title:'PME',body:'Conectividade para equipas, lojas e escritórios.'},{title:'Empresarial',body:'Soluções dedicadas, SLA e suporte prioritário.'}])}</section>`;
function solution(){return shell(`<section class="pagehead"><p class="eyebrow">Solução própria</p><h1>Minha Farmácia Online</h1><p>Uma plataforma modular para farmácias venderem online, gerir produtos, receitas, entregas e relacionamento com clientes.</p></section>${cards([{title:'Funcionalidades',body:'Catálogo, stock, carrinho, encomendas, receitas, pagamentos, entregas e relatórios.'},{title:'Benefícios',body:'Mais vendas, atendimento digital, controlo operacional e experiência moderna para o cliente.'},{title:'Arquitetura',body:'Base modular preparada para integrações, APIs, cloud, dashboards e expansão multi-filial.'},{title:'Público-alvo',body:'Farmácias independentes, redes, clínicas e negócios de saúde que precisam de presença digital.'}])}`)}
function simple(title,body){return shell(`<section class="pagehead"><h1>${title}</h1><p>${body}</p></section>${cards([{title:'Estrutura pronta',body:'Página preparada para conteúdos, filtros, casos, formulários e integrações futuras.'},{title:'SEO e conversão',body:'Conteúdo semântico, chamadas claras e arquitetura escalável para landing pages.'},{title:'Credibilidade',body:'Espaço para provas sociais, resultados alcançados, tecnologias e depoimentos.'}])}`)}
function contact(){return shell(`<section class="pagehead"><h1>Contactos</h1><p>Fale com a SixSilvas para solicitar proposta, suporte, instalação AksaNet ou informações sobre a Farmácia SixSilvas.</p></section><section class="contact"><form aria-label="Formulário de contacto"><label>Nome<input required placeholder="O seu nome"></label><label>Email<input type="email" required placeholder="email@empresa.com"></label><label>Mensagem<textarea required placeholder="Como podemos ajudar?"></textarea></label><button class="btn primary">Enviar mensagem</button></form><div class="panel"><h2>Canais</h2><p>WhatsApp: +244 900 000 000<br>Email: geral@sixsilvas.com<br>Telefone: +244 900 000 001<br>Localização: Angola<br>Horário: Segunda a Sábado</p><div class="map">Mapa institucional</div></div></section>`)}
const timeline=(xs)=>`<ol class="timeline">${xs.map(x=>`<li>${x}</li>`).join('')}</ol>`;
function render(){const p=location.pathname;let html=p==='/'?home():p==='/sobre'?about():p.startsWith('/areas/')?area(p.split('/').pop()):p.includes('minha-farmacia-online')?solution():p==='/contactos'?contact():p==='/portfolio'?simple('Portfólio','Projetos, casos de sucesso, tecnologias utilizadas e resultados alcançados.'):p==='/clientes'?simple('Clientes','Secção preparada para logos, casos e depoimentos.'):p==='/parceiros'?simple('Parceiros','Apresentação de parceiros estratégicos e alianças tecnológicas.'):p==='/blog'?simple('Blog','Conteúdos sobre tecnologia, cloud, redes, segurança, software, internet, farmácia e transformação digital.'):p==='/carreiras'?simple('Carreiras','Benefícios, valores, vagas e banco de talentos para profissionais que querem crescer connosco.'):home();app.innerHTML=html;document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.links')?.classList.toggle('open'));document.querySelectorAll('a[data-link]').forEach(a=>a.addEventListener('click',e=>{const href=e.currentTarget.getAttribute('href'); if(href.startsWith('/')){e.preventDefault();history.pushState({},'',href);render();scrollTo(0,0)}}));}
addEventListener('popstate',render);render();
